#
# enhavo
#
enhavo_media:
    resource: "@EnhavoMediaBundle/Resources/config/routing.yml"
    prefix:   /

enhavo_admin:
    resource: "@EnhavoAppBundle/Resources/config/routing/admin.yml"
    prefix: /admin

enhavo_dashboard:
    resource: "@EnhavoDashboardBundle/Resources/config/routing.yml"
    prefix:   /admin

enhavo_user_admin:
    resource: "@EnhavoUserBundle/Resources/config/routing/admin.yml"
    prefix: /admin

enhavo_group_admin_group:
    resource: "@EnhavoUserBundle/Resources/config/routing/admin/group.yml"
    prefix: /admin

#
# 3rd Party
#
_bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

#
# Project
#

project:
    resource: "@ProjectBundle/Resources/config/routing.yml"
    prefix:   /
