ProjectBundle\Entity\Host:
    type: entity
    table: project_host
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        domain:
            type: string
            nullable: true
        https:
            type: integer
            nullable: true
        transferType:
            type: string
            nullable: true
        backendStrategy:
            type: string
            nullable: true
        directorName:
            type: string
            nullable: true
        certificate:
            type: text
            nullable: true
        certificateKey:
            type: text
            nullable: true
        certificateRequest:
            type: text
            nullable: true
        certificateType:
            type: boolean
            nullable: true
        redirect:
            type: string
            nullable: true
        default:
            type: boolean
            nullable: true

    oneToMany:
        backends:
            cascade: ['persist', 'remove', 'refresh']
            targetEntity: Backend
            mappedBy: host

    lifecycleCallbacks: {  }
