ProjectBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: ProjectBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }
